apiVersion: v1
kind: ServiceAccount
metadata:
  name: hybrid-cloud-demo-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hybrid-cloud-demo-deployer
rules:
  - apiGroups: [""]
    resources: ["deployment", "service", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "revisions", "routes"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hybrid-cloud-demo-deployer-binding
subjects:
  - kind: ServiceAccount
    name: hybrid-cloud-demo-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: hybrid-cloud-demo-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: hybrid-cloud-demo-deployer-editor
subjects:
  - kind: ServiceAccount
    name: hybrid-cloud-demo-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-createwebhook-binding
roleRef:
  kind: Role
  name: tekton-triggers-createwebhook
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: hybrid-cloud-demo-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-admin-binding
roleRef:
  kind: Role
  name: tekton-triggers-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: hybrid-cloud-demo-sa
    namespace: default
